language: nodejs
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm run setup
- npm run build
script:
- npm run test-only
deploy:
- provider: heroku
  app:
    master: coc-backend
    development: coc-backend-dev
    simple: coc-backend-dev
  skip_cleanup: true
  api_key:
    secure: mIg7Q+XiptKRgvKtOVOfBPeH6j8FYoPwPLMrlyK5TQU+P42bgZCg5U+A0mFN970OAr0e5zxrt3v1eYxzLtQvZaKAkVOsY/FRRuXYX64DlAz85/l2V0T/mjxj/dGhhsps3IP1DEKNjU06h2PKL2fkyaL3ZmEkJ6Pdr/kLX4XKXPupXRID0jW85/cWcTH9Tr+MjEt5tdqvbIWRcmVhuh+oUGQvp6gTfW7KQb3CPlI6U5CCqtaylyULTbsLdJ6mlbtFnDx5C9lPbrOYpIGJiXQp9JwIrd0WVcHjhROqejEHptJYlLnLV1UlKN2P7C73H5aUEpZwlKKmh2d8G3m/YglNLwMKH8qA2AwNSPU9jX0kmngINGcy7nxbIRDe4Ec85M+C16WBO+VmBJQ9vPAQg8LayDnJsd9Z+dP0pvxv1m3pkiGDerhpb14MU5GARn81ivGkyQmP/Iz96ss/GMh89EksoHMI8zbmqCnQLU8qyX7OF2pwpfHHa99s2ljlOltHvIJfXjlprm1CxaE2TwNwutwk8jszGtaKRGs3Jzt7CTRjywArH4c0gNBlKSAewhnH6kT+AhYsY7Seda01tKEJN/+csoJdCeRmZ1cgYOp53GzcHVoP2TF8v0AhYRiGjSrh9CECIQ4afAqNheeqKRvsGEP48lbuHRwIEzLV+gAwmnSnkSY=
